//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralParking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CentralParkingEntities : DbContext
    {
        public CentralParkingEntities()
            : base("name=CentralParkingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<locador> locadors1 { get; set; }
        public virtual DbSet<Locatario> Locatarios { get; set; }
        public virtual DbSet<Vaga> Vagas { get; set; }
        public virtual DbSet<Veiculo> Veiculoes { get; set; }
        public virtual DbSet<Aluguel> Aluguels { get; set; }
    }
}
